name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Automatic GitHub Release
      uses: justincy/github-action-npm-release@2.0.1
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Deploy Workflow
      if: steps.release.outputs.released == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy.yml',
            ref: '${{ steps.release.outputs.release_tag }}'
          })