name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Automatic GitHub Release
      uses: justincy/github-action-npm-release@2.0.1
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}